# Copyright (c) 2024 Ahmad Ahmad <ahmadgh@bu.edu>
# SPDX-License-Identifier: MIT
#
# This file was generated by ANTLR 4 from twtl.g4.
# Regenerate with: antlr4 -Dlanguage=Python3 twtl.g4
# Generated from twtl.g4 by ANTLR 4.7.1
from antlr4 import *
if __name__ is not None and "." in __name__:
    from .twtlParser import twtlParser
else:
    from twtlParser import twtlParser

# This class defines a complete listener for a parse tree produced by twtlParser.
class twtlListener(ParseTreeListener):

    # Enter a parse tree produced by twtlParser#formula.
    def enterFormula(self, ctx:twtlParser.FormulaContext):
        pass

    # Exit a parse tree produced by twtlParser#formula.
    def exitFormula(self, ctx:twtlParser.FormulaContext):
        pass


    # Enter a parse tree produced by twtlParser#nf.
    def enterNf(self, ctx:twtlParser.NfContext):
        pass

    # Exit a parse tree produced by twtlParser#nf.
    def exitNf(self, ctx:twtlParser.NfContext):
        pass


    # Enter a parse tree produced by twtlParser#booleanExpr.
    def enterBooleanExpr(self, ctx:twtlParser.BooleanExprContext):
        pass

    # Exit a parse tree produced by twtlParser#booleanExpr.
    def exitBooleanExpr(self, ctx:twtlParser.BooleanExprContext):
        pass


    # Enter a parse tree produced by twtlParser#expr.
    def enterExpr(self, ctx:twtlParser.ExprContext):
        pass

    # Exit a parse tree produced by twtlParser#expr.
    def exitExpr(self, ctx:twtlParser.ExprContext):
        pass


