# Copyright (c) 2024 Ahmad Ahmad <ahmadgh@bu.edu>
# SPDX-License-Identifier: MIT
#
# This file was generated by ANTLR 4 from twtl.g4.
# Regenerate with: antlr4 -Dlanguage=Python3 twtl.g4
# Generated from twtl.g4 by ANTLR 4.7.1
# encoding: utf-8
from antlr4 import *
from io import StringIO
from typing.io import TextIO
import sys


def serializedATN():
    with StringIO() as buf:
        buf.write("\3\u608b\ua72a\u8133\ub9ed\u417c\u3be7\u7786\u5964\3\35")
        buf.write("k\4\2\t\2\4\3\t\3\4\4\t\4\4\5\t\5\3\2\3\2\3\2\3\2\3\2")
        buf.write("\3\2\3\2\3\2\5\2\23\n\2\3\2\5\2\26\n\2\3\2\3\2\3\2\3\2")
        buf.write("\3\2\3\2\3\2\3\2\3\2\3\2\3\2\3\2\3\2\5\2%\n\2\3\2\3\2")
        buf.write("\3\2\3\2\3\2\3\2\3\2\3\2\3\2\7\2\60\n\2\f\2\16\2\63\13")
        buf.write("\2\3\3\3\3\3\3\3\3\5\39\n\3\3\3\3\3\3\3\3\3\3\3\3\3\7")
        buf.write("\3A\n\3\f\3\16\3D\13\3\3\4\3\4\3\4\3\4\3\4\3\4\3\4\5\4")
        buf.write("M\n\4\3\5\3\5\3\5\3\5\3\5\3\5\3\5\3\5\3\5\3\5\3\5\3\5")
        buf.write("\5\5[\n\5\3\5\3\5\3\5\3\5\3\5\3\5\3\5\3\5\3\5\7\5f\n\5")
        buf.write("\f\5\16\5i\13\5\3\5\2\5\2\4\b\6\2\4\6\b\2\6\3\2\t\r\4")
        buf.write("\2\3\3\16\16\3\2\17\20\3\2\21\22\2{\2$\3\2\2\2\48\3\2")
        buf.write("\2\2\6L\3\2\2\2\bZ\3\2\2\2\n\13\b\2\1\2\13\f\7\3\2\2\f")
        buf.write("\r\5\2\2\2\r\16\7\4\2\2\16%\3\2\2\2\17\20\7\26\2\2\20")
        buf.write("\21\7\5\2\2\21\23\7\30\2\2\22\17\3\2\2\2\22\23\3\2\2\2")
        buf.write("\23\25\3\2\2\2\24\26\7\25\2\2\25\24\3\2\2\2\25\26\3\2")
        buf.write("\2\2\26\27\3\2\2\2\27%\5\4\3\2\30\31\7\25\2\2\31%\5\2")
        buf.write("\2\6\32\33\7\6\2\2\33\34\5\2\2\2\34\35\7\7\2\2\35\36\7")
        buf.write("\5\2\2\36\37\7\6\2\2\37 \7\30\2\2 !\7\b\2\2!\"\7\30\2")
        buf.write("\2\"#\7\7\2\2#%\3\2\2\2$\n\3\2\2\2$\22\3\2\2\2$\30\3\2")
        buf.write("\2\2$\32\3\2\2\2%\61\3\2\2\2&\'\f\b\2\2\'(\7\27\2\2(\60")
        buf.write("\5\2\2\t)*\f\4\2\2*+\7\24\2\2+\60\5\2\2\5,-\f\3\2\2-.")
        buf.write("\7\23\2\2.\60\5\2\2\4/&\3\2\2\2/)\3\2\2\2/,\3\2\2\2\60")
        buf.write("\63\3\2\2\2\61/\3\2\2\2\61\62\3\2\2\2\62\3\3\2\2\2\63")
        buf.write("\61\3\2\2\2\64\65\b\3\1\2\659\7\32\2\2\669\7\31\2\2\67")
        buf.write("9\5\6\4\28\64\3\2\2\28\66\3\2\2\28\67\3\2\2\29B\3\2\2")
        buf.write("\2:;\f\4\2\2;<\7\24\2\2<A\5\4\3\5=>\f\3\2\2>?\7\23\2\2")
        buf.write("?A\5\4\3\4@:\3\2\2\2@=\3\2\2\2AD\3\2\2\2B@\3\2\2\2BC\3")
        buf.write("\2\2\2C\5\3\2\2\2DB\3\2\2\2EM\7\32\2\2FM\7\31\2\2GM\7")
        buf.write("\33\2\2HI\5\b\5\2IJ\t\2\2\2JK\5\b\5\2KM\3\2\2\2LE\3\2")
        buf.write("\2\2LF\3\2\2\2LG\3\2\2\2LH\3\2\2\2M\7\3\2\2\2NO\b\5\1")
        buf.write("\2OP\t\3\2\2PQ\5\b\5\2QR\7\4\2\2R[\3\2\2\2ST\7\33\2\2")
        buf.write("TU\7\3\2\2UV\5\b\5\2VW\7\4\2\2W[\3\2\2\2X[\7\30\2\2Y[")
        buf.write("\7\33\2\2ZN\3\2\2\2ZS\3\2\2\2ZX\3\2\2\2ZY\3\2\2\2[g\3")
        buf.write("\2\2\2\\]\f\b\2\2]^\7\5\2\2^f\5\b\5\b_`\f\6\2\2`a\t\4")
        buf.write("\2\2af\5\b\5\7bc\f\5\2\2cd\t\5\2\2df\5\b\5\6e\\\3\2\2")
        buf.write("\2e_\3\2\2\2eb\3\2\2\2fi\3\2\2\2ge\3\2\2\2gh\3\2\2\2h")
        buf.write("\t\3\2\2\2ig\3\2\2\2\16\22\25$/\618@BLZeg")
        return buf.getvalue()


class twtlParser ( Parser ):

    grammarFileName = "twtl.g4"

    atn = ATNDeserializer().deserialize(serializedATN())

    decisionsToDFA = [ DFA(ds, i) for i, ds in enumerate(atn.decisionToState) ]

    sharedContextCache = PredictionContextCache()

    literalNames = [ "<INVALID>", "'('", "')'", "'^'", "'['", "']'", "','", 
                     "'<'", "'<='", "'='", "'>='", "'>'", "'-('", "'*'", 
                     "'/'", "'+'", "'-'", "<INVALID>", "<INVALID>", "<INVALID>", 
                     "'H'", "'.'" ]

    symbolicNames = [ "<INVALID>", "<INVALID>", "<INVALID>", "<INVALID>", 
                      "<INVALID>", "<INVALID>", "<INVALID>", "<INVALID>", 
                      "<INVALID>", "<INVALID>", "<INVALID>", "<INVALID>", 
                      "<INVALID>", "<INVALID>", "<INVALID>", "<INVALID>", 
                      "<INVALID>", "AND", "OR", "NOT", "HOLD", "CONCAT", 
                      "RATIONAL", "TRUE", "FALSE", "VARIABLE", "LINECMT", 
                      "WS" ]

    RULE_formula = 0
    RULE_nf = 1
    RULE_booleanExpr = 2
    RULE_expr = 3

    ruleNames =  [ "formula", "nf", "booleanExpr", "expr" ]

    EOF = Token.EOF
    T__0=1
    T__1=2
    T__2=3
    T__3=4
    T__4=5
    T__5=6
    T__6=7
    T__7=8
    T__8=9
    T__9=10
    T__10=11
    T__11=12
    T__12=13
    T__13=14
    T__14=15
    T__15=16
    AND=17
    OR=18
    NOT=19
    HOLD=20
    CONCAT=21
    RATIONAL=22
    TRUE=23
    FALSE=24
    VARIABLE=25
    LINECMT=26
    WS=27

    def __init__(self, input:TokenStream, output:TextIO = sys.stdout):
        super().__init__(input, output)
        self.checkVersion("4.7.1")
        self._interp = ParserATNSimulator(self, self.atn, self.decisionsToDFA, self.sharedContextCache)
        self._predicates = None



    class FormulaContext(ParserRuleContext):

        def __init__(self, parser, parent:ParserRuleContext=None, invokingState:int=-1):
            super().__init__(parent, invokingState)
            self.parser = parser
            self.left = None # FormulaContext
            self.op = None # Token
            self.child = None # FormulaContext
            self.duration = None # Token
            self.negated = None # Token
            self.prop = None # NfContext
            self.low = None # Token
            self.high = None # Token
            self.right = None # FormulaContext

        def formula(self, i:int=None):
            if i is None:
                return self.getTypedRuleContexts(twtlParser.FormulaContext)
            else:
                return self.getTypedRuleContext(twtlParser.FormulaContext,i)


        def nf(self):
            return self.getTypedRuleContext(twtlParser.NfContext,0)


        def HOLD(self):
            return self.getToken(twtlParser.HOLD, 0)

        def RATIONAL(self, i:int=None):
            if i is None:
                return self.getTokens(twtlParser.RATIONAL)
            else:
                return self.getToken(twtlParser.RATIONAL, i)

        def NOT(self):
            return self.getToken(twtlParser.NOT, 0)

        def CONCAT(self):
            return self.getToken(twtlParser.CONCAT, 0)

        def OR(self):
            return self.getToken(twtlParser.OR, 0)

        def AND(self):
            return self.getToken(twtlParser.AND, 0)

        def getRuleIndex(self):
            return twtlParser.RULE_formula

        def enterRule(self, listener:ParseTreeListener):
            if hasattr( listener, "enterFormula" ):
                listener.enterFormula(self)

        def exitRule(self, listener:ParseTreeListener):
            if hasattr( listener, "exitFormula" ):
                listener.exitFormula(self)

        def accept(self, visitor:ParseTreeVisitor):
            if hasattr( visitor, "visitFormula" ):
                return visitor.visitFormula(self)
            else:
                return visitor.visitChildren(self)



    def formula(self, _p:int=0):
        _parentctx = self._ctx
        _parentState = self.state
        localctx = twtlParser.FormulaContext(self, self._ctx, _parentState)
        _prevctx = localctx
        _startState = 0
        self.enterRecursionRule(localctx, 0, self.RULE_formula, _p)
        self._la = 0 # Token type
        try:
            self.enterOuterAlt(localctx, 1)
            self.state = 34
            self._errHandler.sync(self)
            la_ = self._interp.adaptivePredict(self._input,2,self._ctx)
            if la_ == 1:
                self.state = 9
                localctx.op = self.match(twtlParser.T__0)
                self.state = 10
                localctx.child = self.formula(0)
                self.state = 11
                self.match(twtlParser.T__1)
                pass

            elif la_ == 2:
                self.state = 16
                self._errHandler.sync(self)
                _la = self._input.LA(1)
                if _la==twtlParser.HOLD:
                    self.state = 13
                    localctx.op = self.match(twtlParser.HOLD)
                    self.state = 14
                    self.match(twtlParser.T__2)
                    self.state = 15
                    localctx.duration = self.match(twtlParser.RATIONAL)


                self.state = 19
                self._errHandler.sync(self)
                _la = self._input.LA(1)
                if _la==twtlParser.NOT:
                    self.state = 18
                    localctx.negated = self.match(twtlParser.NOT)


                self.state = 21
                localctx.prop = self.nf(0)
                pass

            elif la_ == 3:
                self.state = 22
                localctx.op = self.match(twtlParser.NOT)
                self.state = 23
                localctx.child = self.formula(4)
                pass

            elif la_ == 4:
                self.state = 24
                localctx.op = self.match(twtlParser.T__3)
                self.state = 25
                localctx.child = self.formula(0)
                self.state = 26
                self.match(twtlParser.T__4)
                self.state = 27
                self.match(twtlParser.T__2)
                self.state = 28
                self.match(twtlParser.T__3)
                self.state = 29
                localctx.low = self.match(twtlParser.RATIONAL)
                self.state = 30
                self.match(twtlParser.T__5)
                self.state = 31
                localctx.high = self.match(twtlParser.RATIONAL)
                self.state = 32
                self.match(twtlParser.T__4)
                pass


            self._ctx.stop = self._input.LT(-1)
            self.state = 47
            self._errHandler.sync(self)
            _alt = self._interp.adaptivePredict(self._input,4,self._ctx)
            while _alt!=2 and _alt!=ATN.INVALID_ALT_NUMBER:
                if _alt==1:
                    if self._parseListeners is not None:
                        self.triggerExitRuleEvent()
                    _prevctx = localctx
                    self.state = 45
                    self._errHandler.sync(self)
                    la_ = self._interp.adaptivePredict(self._input,3,self._ctx)
                    if la_ == 1:
                        localctx = twtlParser.FormulaContext(self, _parentctx, _parentState)
                        localctx.left = _prevctx
                        self.pushNewRecursionContext(localctx, _startState, self.RULE_formula)
                        self.state = 36
                        if not self.precpred(self._ctx, 6):
                            from antlr4.error.Errors import FailedPredicateException
                            raise FailedPredicateException(self, "self.precpred(self._ctx, 6)")
                        self.state = 37
                        localctx.op = self.match(twtlParser.CONCAT)
                        self.state = 38
                        localctx.right = self.formula(7)
                        pass

                    elif la_ == 2:
                        localctx = twtlParser.FormulaContext(self, _parentctx, _parentState)
                        localctx.left = _prevctx
                        self.pushNewRecursionContext(localctx, _startState, self.RULE_formula)
                        self.state = 39
                        if not self.precpred(self._ctx, 2):
                            from antlr4.error.Errors import FailedPredicateException
                            raise FailedPredicateException(self, "self.precpred(self._ctx, 2)")
                        self.state = 40
                        localctx.op = self.match(twtlParser.OR)
                        self.state = 41
                        localctx.right = self.formula(3)
                        pass

                    elif la_ == 3:
                        localctx = twtlParser.FormulaContext(self, _parentctx, _parentState)
                        localctx.left = _prevctx
                        self.pushNewRecursionContext(localctx, _startState, self.RULE_formula)
                        self.state = 42
                        if not self.precpred(self._ctx, 1):
                            from antlr4.error.Errors import FailedPredicateException
                            raise FailedPredicateException(self, "self.precpred(self._ctx, 1)")
                        self.state = 43
                        localctx.op = self.match(twtlParser.AND)
                        self.state = 44
                        localctx.right = self.formula(2)
                        pass

             
                self.state = 49
                self._errHandler.sync(self)
                _alt = self._interp.adaptivePredict(self._input,4,self._ctx)

        except RecognitionException as re:
            localctx.exception = re
            self._errHandler.reportError(self, re)
            self._errHandler.recover(self, re)
        finally:
            self.unrollRecursionContexts(_parentctx)
        return localctx

    class NfContext(ParserRuleContext):

        def __init__(self, parser, parent:ParserRuleContext=None, invokingState:int=-1):
            super().__init__(parent, invokingState)
            self.parser = parser
            self.left = None # NfContext
            self.op = None # Token
            self.right = None # NfContext

        def FALSE(self):
            return self.getToken(twtlParser.FALSE, 0)

        def TRUE(self):
            return self.getToken(twtlParser.TRUE, 0)

        def booleanExpr(self):
            return self.getTypedRuleContext(twtlParser.BooleanExprContext,0)


        def nf(self, i:int=None):
            if i is None:
                return self.getTypedRuleContexts(twtlParser.NfContext)
            else:
                return self.getTypedRuleContext(twtlParser.NfContext,i)


        def OR(self):
            return self.getToken(twtlParser.OR, 0)

        def AND(self):
            return self.getToken(twtlParser.AND, 0)

        def getRuleIndex(self):
            return twtlParser.RULE_nf

        def enterRule(self, listener:ParseTreeListener):
            if hasattr( listener, "enterNf" ):
                listener.enterNf(self)

        def exitRule(self, listener:ParseTreeListener):
            if hasattr( listener, "exitNf" ):
                listener.exitNf(self)

        def accept(self, visitor:ParseTreeVisitor):
            if hasattr( visitor, "visitNf" ):
                return visitor.visitNf(self)
            else:
                return visitor.visitChildren(self)



    def nf(self, _p:int=0):
        _parentctx = self._ctx
        _parentState = self.state
        localctx = twtlParser.NfContext(self, self._ctx, _parentState)
        _prevctx = localctx
        _startState = 2
        self.enterRecursionRule(localctx, 2, self.RULE_nf, _p)
        try:
            self.enterOuterAlt(localctx, 1)
            self.state = 54
            self._errHandler.sync(self)
            la_ = self._interp.adaptivePredict(self._input,5,self._ctx)
            if la_ == 1:
                self.state = 51
                localctx.op = self.match(twtlParser.FALSE)
                pass

            elif la_ == 2:
                self.state = 52
                localctx.op = self.match(twtlParser.TRUE)
                pass

            elif la_ == 3:
                self.state = 53
                self.booleanExpr()
                pass


            self._ctx.stop = self._input.LT(-1)
            self.state = 64
            self._errHandler.sync(self)
            _alt = self._interp.adaptivePredict(self._input,7,self._ctx)
            while _alt!=2 and _alt!=ATN.INVALID_ALT_NUMBER:
                if _alt==1:
                    if self._parseListeners is not None:
                        self.triggerExitRuleEvent()
                    _prevctx = localctx
                    self.state = 62
                    self._errHandler.sync(self)
                    la_ = self._interp.adaptivePredict(self._input,6,self._ctx)
                    if la_ == 1:
                        localctx = twtlParser.NfContext(self, _parentctx, _parentState)
                        localctx.left = _prevctx
                        self.pushNewRecursionContext(localctx, _startState, self.RULE_nf)
                        self.state = 56
                        if not self.precpred(self._ctx, 2):
                            from antlr4.error.Errors import FailedPredicateException
                            raise FailedPredicateException(self, "self.precpred(self._ctx, 2)")
                        self.state = 57
                        localctx.op = self.match(twtlParser.OR)
                        self.state = 58
                        localctx.right = self.nf(3)
                        pass

                    elif la_ == 2:
                        localctx = twtlParser.NfContext(self, _parentctx, _parentState)
                        localctx.left = _prevctx
                        self.pushNewRecursionContext(localctx, _startState, self.RULE_nf)
                        self.state = 59
                        if not self.precpred(self._ctx, 1):
                            from antlr4.error.Errors import FailedPredicateException
                            raise FailedPredicateException(self, "self.precpred(self._ctx, 1)")
                        self.state = 60
                        localctx.op = self.match(twtlParser.AND)
                        self.state = 61
                        localctx.right = self.nf(2)
                        pass

             
                self.state = 66
                self._errHandler.sync(self)
                _alt = self._interp.adaptivePredict(self._input,7,self._ctx)

        except RecognitionException as re:
            localctx.exception = re
            self._errHandler.reportError(self, re)
            self._errHandler.recover(self, re)
        finally:
            self.unrollRecursionContexts(_parentctx)
        return localctx

    class BooleanExprContext(ParserRuleContext):

        def __init__(self, parser, parent:ParserRuleContext=None, invokingState:int=-1):
            super().__init__(parent, invokingState)
            self.parser = parser
            self.op = None # Token
            self.left = None # ExprContext
            self.right = None # ExprContext

        def FALSE(self):
            return self.getToken(twtlParser.FALSE, 0)

        def TRUE(self):
            return self.getToken(twtlParser.TRUE, 0)

        def VARIABLE(self):
            return self.getToken(twtlParser.VARIABLE, 0)

        def expr(self, i:int=None):
            if i is None:
                return self.getTypedRuleContexts(twtlParser.ExprContext)
            else:
                return self.getTypedRuleContext(twtlParser.ExprContext,i)


        def getRuleIndex(self):
            return twtlParser.RULE_booleanExpr

        def enterRule(self, listener:ParseTreeListener):
            if hasattr( listener, "enterBooleanExpr" ):
                listener.enterBooleanExpr(self)

        def exitRule(self, listener:ParseTreeListener):
            if hasattr( listener, "exitBooleanExpr" ):
                listener.exitBooleanExpr(self)

        def accept(self, visitor:ParseTreeVisitor):
            if hasattr( visitor, "visitBooleanExpr" ):
                return visitor.visitBooleanExpr(self)
            else:
                return visitor.visitChildren(self)




    def booleanExpr(self):

        localctx = twtlParser.BooleanExprContext(self, self._ctx, self.state)
        self.enterRule(localctx, 4, self.RULE_booleanExpr)
        self._la = 0 # Token type
        try:
            self.state = 74
            self._errHandler.sync(self)
            la_ = self._interp.adaptivePredict(self._input,8,self._ctx)
            if la_ == 1:
                self.enterOuterAlt(localctx, 1)
                self.state = 67
                localctx.op = self.match(twtlParser.FALSE)
                pass

            elif la_ == 2:
                self.enterOuterAlt(localctx, 2)
                self.state = 68
                localctx.op = self.match(twtlParser.TRUE)
                pass

            elif la_ == 3:
                self.enterOuterAlt(localctx, 3)
                self.state = 69
                localctx.op = self.match(twtlParser.VARIABLE)
                pass

            elif la_ == 4:
                self.enterOuterAlt(localctx, 4)
                self.state = 70
                localctx.left = self.expr(0)
                self.state = 71
                localctx.op = self._input.LT(1)
                _la = self._input.LA(1)
                if not((((_la) & ~0x3f) == 0 and ((1 << _la) & ((1 << twtlParser.T__6) | (1 << twtlParser.T__7) | (1 << twtlParser.T__8) | (1 << twtlParser.T__9) | (1 << twtlParser.T__10))) != 0)):
                    localctx.op = self._errHandler.recoverInline(self)
                else:
                    self._errHandler.reportMatch(self)
                    self.consume()
                self.state = 72
                localctx.right = self.expr(0)
                pass


        except RecognitionException as re:
            localctx.exception = re
            self._errHandler.reportError(self, re)
            self._errHandler.recover(self, re)
        finally:
            self.exitRule()
        return localctx

    class ExprContext(ParserRuleContext):

        def __init__(self, parser, parent:ParserRuleContext=None, invokingState:int=-1):
            super().__init__(parent, invokingState)
            self.parser = parser

        def expr(self, i:int=None):
            if i is None:
                return self.getTypedRuleContexts(twtlParser.ExprContext)
            else:
                return self.getTypedRuleContext(twtlParser.ExprContext,i)


        def VARIABLE(self):
            return self.getToken(twtlParser.VARIABLE, 0)

        def RATIONAL(self):
            return self.getToken(twtlParser.RATIONAL, 0)

        def getRuleIndex(self):
            return twtlParser.RULE_expr

        def enterRule(self, listener:ParseTreeListener):
            if hasattr( listener, "enterExpr" ):
                listener.enterExpr(self)

        def exitRule(self, listener:ParseTreeListener):
            if hasattr( listener, "exitExpr" ):
                listener.exitExpr(self)

        def accept(self, visitor:ParseTreeVisitor):
            if hasattr( visitor, "visitExpr" ):
                return visitor.visitExpr(self)
            else:
                return visitor.visitChildren(self)



    def expr(self, _p:int=0):
        _parentctx = self._ctx
        _parentState = self.state
        localctx = twtlParser.ExprContext(self, self._ctx, _parentState)
        _prevctx = localctx
        _startState = 6
        self.enterRecursionRule(localctx, 6, self.RULE_expr, _p)
        self._la = 0 # Token type
        try:
            self.enterOuterAlt(localctx, 1)
            self.state = 88
            self._errHandler.sync(self)
            la_ = self._interp.adaptivePredict(self._input,9,self._ctx)
            if la_ == 1:
                self.state = 77
                _la = self._input.LA(1)
                if not(_la==twtlParser.T__0 or _la==twtlParser.T__11):
                    self._errHandler.recoverInline(self)
                else:
                    self._errHandler.reportMatch(self)
                    self.consume()
                self.state = 78
                self.expr(0)
                self.state = 79
                self.match(twtlParser.T__1)
                pass

            elif la_ == 2:
                self.state = 81
                self.match(twtlParser.VARIABLE)
                self.state = 82
                self.match(twtlParser.T__0)
                self.state = 83
                self.expr(0)
                self.state = 84
                self.match(twtlParser.T__1)
                pass

            elif la_ == 3:
                self.state = 86
                self.match(twtlParser.RATIONAL)
                pass

            elif la_ == 4:
                self.state = 87
                self.match(twtlParser.VARIABLE)
                pass


            self._ctx.stop = self._input.LT(-1)
            self.state = 101
            self._errHandler.sync(self)
            _alt = self._interp.adaptivePredict(self._input,11,self._ctx)
            while _alt!=2 and _alt!=ATN.INVALID_ALT_NUMBER:
                if _alt==1:
                    if self._parseListeners is not None:
                        self.triggerExitRuleEvent()
                    _prevctx = localctx
                    self.state = 99
                    self._errHandler.sync(self)
                    la_ = self._interp.adaptivePredict(self._input,10,self._ctx)
                    if la_ == 1:
                        localctx = twtlParser.ExprContext(self, _parentctx, _parentState)
                        self.pushNewRecursionContext(localctx, _startState, self.RULE_expr)
                        self.state = 90
                        if not self.precpred(self._ctx, 6):
                            from antlr4.error.Errors import FailedPredicateException
                            raise FailedPredicateException(self, "self.precpred(self._ctx, 6)")
                        self.state = 91
                        self.match(twtlParser.T__2)
                        self.state = 92
                        self.expr(6)
                        pass

                    elif la_ == 2:
                        localctx = twtlParser.ExprContext(self, _parentctx, _parentState)
                        self.pushNewRecursionContext(localctx, _startState, self.RULE_expr)
                        self.state = 93
                        if not self.precpred(self._ctx, 4):
                            from antlr4.error.Errors import FailedPredicateException
                            raise FailedPredicateException(self, "self.precpred(self._ctx, 4)")
                        self.state = 94
                        _la = self._input.LA(1)
                        if not(_la==twtlParser.T__12 or _la==twtlParser.T__13):
                            self._errHandler.recoverInline(self)
                        else:
                            self._errHandler.reportMatch(self)
                            self.consume()
                        self.state = 95
                        self.expr(5)
                        pass

                    elif la_ == 3:
                        localctx = twtlParser.ExprContext(self, _parentctx, _parentState)
                        self.pushNewRecursionContext(localctx, _startState, self.RULE_expr)
                        self.state = 96
                        if not self.precpred(self._ctx, 3):
                            from antlr4.error.Errors import FailedPredicateException
                            raise FailedPredicateException(self, "self.precpred(self._ctx, 3)")
                        self.state = 97
                        _la = self._input.LA(1)
                        if not(_la==twtlParser.T__14 or _la==twtlParser.T__15):
                            self._errHandler.recoverInline(self)
                        else:
                            self._errHandler.reportMatch(self)
                            self.consume()
                        self.state = 98
                        self.expr(4)
                        pass

             
                self.state = 103
                self._errHandler.sync(self)
                _alt = self._interp.adaptivePredict(self._input,11,self._ctx)

        except RecognitionException as re:
            localctx.exception = re
            self._errHandler.reportError(self, re)
            self._errHandler.recover(self, re)
        finally:
            self.unrollRecursionContexts(_parentctx)
        return localctx



    def sempred(self, localctx:RuleContext, ruleIndex:int, predIndex:int):
        if self._predicates == None:
            self._predicates = dict()
        self._predicates[0] = self.formula_sempred
        self._predicates[1] = self.nf_sempred
        self._predicates[3] = self.expr_sempred
        pred = self._predicates.get(ruleIndex, None)
        if pred is None:
            raise Exception("No predicate with index:" + str(ruleIndex))
        else:
            return pred(localctx, predIndex)

    def formula_sempred(self, localctx:FormulaContext, predIndex:int):
            if predIndex == 0:
                return self.precpred(self._ctx, 6)
         

            if predIndex == 1:
                return self.precpred(self._ctx, 2)
         

            if predIndex == 2:
                return self.precpred(self._ctx, 1)
         

    def nf_sempred(self, localctx:NfContext, predIndex:int):
            if predIndex == 3:
                return self.precpred(self._ctx, 2)
         

            if predIndex == 4:
                return self.precpred(self._ctx, 1)
         

    def expr_sempred(self, localctx:ExprContext, predIndex:int):
            if predIndex == 5:
                return self.precpred(self._ctx, 6)
         

            if predIndex == 6:
                return self.precpred(self._ctx, 4)
         

            if predIndex == 7:
                return self.precpred(self._ctx, 3)
         




