# Copyright (c) 2024 Ahmad Ahmad <ahmadgh@bu.edu>
# SPDX-License-Identifier: MIT
#
# This file was generated by ANTLR 4 from twtl.g4.
# Regenerate with: antlr4 -Dlanguage=Python3 twtl.g4
# Generated from twtl.g4 by ANTLR 4.7.1
from antlr4 import *
if __name__ is not None and "." in __name__:
    from .twtlParser import twtlParser
else:
    from twtlParser import twtlParser

# This class defines a complete generic visitor for a parse tree produced by twtlParser.

class twtlVisitor(ParseTreeVisitor):

    # Visit a parse tree produced by twtlParser#formula.
    def visitFormula(self, ctx:twtlParser.FormulaContext):
        return self.visitChildren(ctx)


    # Visit a parse tree produced by twtlParser#nf.
    def visitNf(self, ctx:twtlParser.NfContext):
        return self.visitChildren(ctx)


    # Visit a parse tree produced by twtlParser#booleanExpr.
    def visitBooleanExpr(self, ctx:twtlParser.BooleanExprContext):
        return self.visitChildren(ctx)


    # Visit a parse tree produced by twtlParser#expr.
    def visitExpr(self, ctx:twtlParser.ExprContext):
        return self.visitChildren(ctx)



del twtlParser